# Generated by Django 2.1 on 2023-07-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0020_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='caregiver',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='catname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='district',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='lactating',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='pregnancy_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='project',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
