# Generated by Django 2.1 on 2023-07-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0021_auto_20230712_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
