# Generated by Django 2.1 on 2023-07-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0022_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcastmessagecat',
            name='Subject',
        ),
        migrations.AddField(
            model_name='broadcastmessagecat',
            name='theme',
            field=models.ManyToManyField(to='smsapp.theme'),
        ),
    ]
