# Generated by Django 2.1 on 2023-07-24 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0024_auto_20230724_0358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broadcastmessagecat',
            name='category',
        ),
        migrations.AddField(
            model_name='broadcastmessagecat',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='smsapp.category'),
        ),
    ]
