# Generated by Django 2.1 on 2023-07-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0025_auto_20230724_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
