# Generated by Django 2.1 on 2023-09-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0027_responselog'),
    ]

    operations = [
        migrations.AddField(
            model_name='responselog',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='responselog',
            name='recipient',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='responselog',
            name='smstype',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
