# Generated by Django 2.1 on 2023-09-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0028_auto_20230911_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='call_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
