# Generated by Django 2.1 on 2023-09-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0029_delivery_call_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='answer_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delivery',
            name='hang_up_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
