# Generated by Django 2.1 on 2023-09-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0030_auto_20230913_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='answer_period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
