# Generated by Django 2.1 on 2023-09-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0032_auto_20230914_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='answer_period',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='answer_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='hang_up_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
