# Generated by Django 2.1 on 2023-09-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0033_auto_20230914_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='answer_period',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
