# Generated by Django 2.1 on 2023-09-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0034_auto_20230914_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='answer_period',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True),
        ),
    ]
