# Generated by Django 2.1 on 2023-09-14 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0035_auto_20230914_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='answer_period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
