# Generated by Django 2.1 on 2023-09-14 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0037_auto_20230914_1334'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='delivery',
            options={'verbose_name_plural': 'Deliveries'},
        ),
    ]
