# Generated by Django 2.1 on 2023-09-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smsapp', '0038_auto_20230914_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='answer_period',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='answer_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='hang_up_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
